service: aws-lambda-bolierplate

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage,'local'}
  region: us-east-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'apigateway:GET'
      Resource:
        - 'arn:aws:apigateway:${self:provider.region}::/restapis*'
  environment:
    MONGODB_URI: ${file(./env.${self:provider.stage}.yml):MONGODB_URI}

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-aws-documentation
  # - serverless-domain-manager
  - serverless-stack-output

package:
  include: src/**/*.js
  exclude:
    - test/**/*

functions:
  authorize:
    handler: src/auth/auth.authorize
    description: Validate User Token
    cors: true
  registerUser:
    handler: src/auth/auth.register
    description: Register a new User.
    events:
      - http:
          path: auth/register
          method: post
          cors: true
          documentation:
            summary: Register a new user.
            tags:
              - Auth
            description: Returns the new user.
            methodResponses:
              - statusCode: '200'
                description: Returned when the operation is completed successfully.
                responseModels:
                  'application/json': RegisterOutput
              - ${file(./swagger/error-responses/bad-request.yml)}
              - ${file(./swagger/error-responses/forbidden.yml)}
              - ${file(./swagger/error-responses/not-found.yml)}
              - ${file(./swagger/error-responses/internal-server-error.yml)}
  loginUser:
    handler: src/auth/auth.login
    description: Login user and generate jwt token.
    events:
      - http:
          path: auth/login
          method: post
          cors: true
          documentation:
            summary: Login user and generate jwt token.
            tags:
              - Auth
            description: Returns a token.
            methodResponses:
              - statusCode: '200'
                description: Returned when the operation is completed successfully.
                responseModels:
                  'application/json': UserData
              - ${file(./swagger/error-responses/bad-request.yml)}
              - ${file(./swagger/error-responses/forbidden.yml)}
              - ${file(./swagger/error-responses/not-found.yml)}
              - ${file(./swagger/error-responses/internal-server-error.yml)}
  getUserProfile:
    handler: src/users/user.getProfile
    description: Get User Profile
    events:
      - http:
          path: users/profile
          method: get
          cors: true
          authorizer: authorize
          documentation:
            summary: Get User Profile
            tags:
              - User
            description: Returns a user profile.
            methodResponses:
              - statusCode: '200'
                description: Returned when the operation is completed successfully.
                responseModels:
                  'application/json': UserData
              - ${file(./swagger/error-responses/bad-request.yml)}
              - ${file(./swagger/error-responses/forbidden.yml)}
              - ${file(./swagger/error-responses/not-found.yml)}
              - ${file(./swagger/error-responses/internal-server-error.yml)}
  createOrganization:
    handler: src/organizations/organization.create
    description: Create a new Organization
    events:
      - http:
          path: organizations
          method: post
          cors: true
          authorizer: authorize
          documentation:
            summary: Create a new Organization
            tags:
              - Organization
            description: Returns a new organization.
            methodResponses:
              - statusCode: '200'
                description: Returned when the operation is completed successfully.
                responseModels:
                  'application/json': UserData
              - ${file(./swagger/error-responses/bad-request.yml)}
              - ${file(./swagger/error-responses/forbidden.yml)}
              - ${file(./swagger/error-responses/not-found.yml)}
              - ${file(./swagger/error-responses/internal-server-error.yml)}
custom:
  documentation: ${file(./swagger/documentation.yml)}
  # customDomain:
  #   basePath: "api"
  #   domainName: <your domain>
  #   certificateName: <your domain>
  #   stage: ${self:provider.stage}
  #   createRoute53Record: true
  # output:
  #   file: .serverless/output.json
  webpack:
    webpackConfig: 'webpack.config.ts'
    includeModules: true # enable auto-packing of external modules
